version: 0.2
phases:
  install:
    commands:
      - printenv
  pre_build:
    commands:
      - echo Log in to Amazon ECR YAML Custom...
      - export AWS_ACCOUNT_ID=111111111111
      - export AWS_REGION=us-west-1
      - export ECR_REPOSITORY_NAME=jonas/jonas-fastapi-master
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username
        AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo The value of IMAGE_TAG is:$IMAGE_TAG
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image.
      - echo `pwd`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo write definitions file...
      - echo `pwd`
      - export ECS_CONTAINER_NAME=jonas-fastapi-master
      - printf '[{"name":"%s","imageUri":"%s"}]' $ECS_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
