# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/ \
    APP_ENV=dev \
    ORIGIN=* \
    SCHEDULER=True \
    AWS_ACCESS_KEY_ID=<your_access_key> \
    AWS_SECRET_ACCESS_KEY=<your_secret_key>
    # AWS_S3_BUCKET_NAME=<your_s3_bucket_name> \
    # REDIS_HOST='host.docker.internal' \
    # REDIS_PORT=6379 \
    # REDIS_DB_INDEX=0 \
    # REDIS_DECODE_RESPONSES=Ture \
    # DATABASE_URL= \
    # SECRET_KEY= \
    # DEV_DATABASE_URL= \
    # TEST_DATABASE_URL= \
    # PROD_DATABASE_URL= \
    # KAFKA_ON=False \
    # KAFKA_TOPIC=<your-topic> \
    # KAFKA_BOOTSTRAP_SERVERS=<your-bootstrap-server> \
    # KAFKA_GROUP_ID=<your-group-id>

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY ./app/ /app/

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run the application
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
